/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.UserCRUD;
import Model.User;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author mega
 */
public class GestUserGUI extends javax.swing.JFrame {

    /**
     * Creates new form AddUserGUI
     */
    public GestUserGUI() {
        initComponents();
        showU();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        upwd = new javax.swing.JTextField();
        ajU = new javax.swing.JButton();
        moU = new javax.swing.JButton();
        supU = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        act = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        trechu = new javax.swing.JTextField();
        rechu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Gestion d'utilisateurs");

        jLabel2.setText("Username : ");

        jLabel3.setText("Password : ");

        ajU.setText("Ajouter");
        ajU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajUActionPerformed(evt);
            }
        });

        moU.setText("Modifier");
        moU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moUActionPerformed(evt);
            }
        });

        supU.setText("Supprimer");
        supU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supUActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USERNAME", "PASSWORD"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        act.setText("Actualiser");
        act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actActionPerformed(evt);
            }
        });

        jLabel4.setText("Recherche : ");

        rechu.setText("OK");
        rechu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(458, 458, 458)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(uname)
                            .addComponent(upwd, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(supU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(moU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ajU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(trechu, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rechu)
                                .addGap(5, 5, 5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(act)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ajU)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(upwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(moU)))
                        .addGap(31, 31, 31)
                        .addComponent(supU)
                        .addGap(28, 28, 28)
                        .addComponent(reset)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(trechu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rechu))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addComponent(act)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // Get The Index Of The Slected Row 
        int i = jTable1.getSelectedRow();

        TableModel model = jTable1.getModel();
        
        // Display Slected Row In JTexteFields
        uname.setText(model.getValueAt(i,0).toString());
        upwd.setText(model.getValueAt(i,1).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void ajUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajUActionPerformed
        if(uname.getText().isBlank()||uname.getText().isEmpty()||upwd.getText().isBlank()||upwd.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"champ vide !","Users", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            User u = new User(uname.getText(),upwd.getText());
            UserCRUD uc = new UserCRUD();
            try{
            uc.addU(u);
            JOptionPane.showMessageDialog(this,"User a ete ajouté avec sucess !","Users", JOptionPane.INFORMATION_MESSAGE);
            }catch(HeadlessException e)
            {
                JOptionPane.showMessageDialog(this,"Error !","Users", JOptionPane.ERROR_MESSAGE);
            }
            
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
           model.setRowCount(0);
           showU();
            
        }
    }//GEN-LAST:event_ajUActionPerformed

    private void moUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moUActionPerformed
        if(uname.getText().isBlank()||uname.getText().isEmpty()||upwd.getText().isBlank()||upwd.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"champ vide !","Users", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            
            UserCRUD uc = new UserCRUD();
            try{
            uc.updateU(uname.getText(),upwd.getText());
            JOptionPane.showMessageDialog(this,"User a ete modifié avec sucess !","Users", JOptionPane.INFORMATION_MESSAGE);
            }catch(HeadlessException e)
            {
                JOptionPane.showMessageDialog(this,"Error !","Users", JOptionPane.ERROR_MESSAGE);
            }
            
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
           model.setRowCount(0);
           showU();
            
        }
    }//GEN-LAST:event_moUActionPerformed

    private void supUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supUActionPerformed
        UserCRUD uc = new UserCRUD();
        try{
        uc.deleteU(uname.getText());
        JOptionPane.showMessageDialog(this,"User a ete supprimé avec sucess !","Users", JOptionPane.INFORMATION_MESSAGE);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        showU();
        }catch(HeadlessException e)
        {       
            JOptionPane.showMessageDialog(this,"Error !","Users", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_supUActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        uname.setText("");
        upwd.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void rechuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechuActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        showUserByNom();
        
        
    }//GEN-LAST:event_rechuActionPerformed

    private void actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actActionPerformed
           
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        showU();
    }//GEN-LAST:event_actActionPerformed

    
    public void showU(){
         UserCRUD uc = new UserCRUD();
         ArrayList<User> list = new ArrayList();
         list = uc.showUsers();
         
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         Object[] row = new Object[2];
         for (int i = 0; i < list.size(); i++) {
             row[0]=list.get(i).getNom();
             row[1]=list.get(i).getPwd();
       
             model.addRow(row);
             
         }
    
    }
    
    
    
    public void showUserByNom(){
         UserCRUD ec = new UserCRUD();
         ArrayList<User> list = new ArrayList();
         list = ec.searchU(trechu.getText());
         System.out.println(list);
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         Object[] row = new Object[2];
         for (int i = 0; i < list.size(); i++) {
             row[0]=list.get(i).getNom();
             row[1]=list.get(i).getPwd();
             model.addRow(row);
   
         }
         

    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestUserGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton act;
    private javax.swing.JButton ajU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton moU;
    private javax.swing.JButton rechu;
    private javax.swing.JButton reset;
    private javax.swing.JButton supU;
    private javax.swing.JTextField trechu;
    private javax.swing.JTextField uname;
    private javax.swing.JTextField upwd;
    // End of variables declaration//GEN-END:variables
}
